### PR TITLE
Fix dependencies, update CI

### PR DESCRIPTION
**Pull request by wxmerkt**
Relates to #87

### CODE REVIEW

**Comment by wxmerkt** [comment]
Before we merge this: I am wondering if we want to enforce a Python3 wrapper for ROS1 distros prior to Noetic at all. It won't work proper (as ROS1<noetic == Python2) and will complicate the release process. It will also pull in the python, python-numpy dependencies by default (i.e., greater install size for an otherwise small library). As thus I am wondering whether to deactivate the `build_depend` keys and just default to not building the wrapper when those are not available (behaviour < 3.1.2). Thoughts?

**Comment by mkrogius** [comment]
Hi, sorry for not responding sooner. I am definitely on board with not building the python wrapper by default in these cases.

**Comment by wxmerkt** [comment]
Thanks for the feedback - this is good to merge now. :-)

**Comment by mkrogius** [comment]
Great, thanks for putting this together!

**Pull request merged**
