### PR TITLE
Rpi

### PR DESCRIPTION
**Pull request by edwinolson**
This pull request adds an mmal-based image acquisition pipeline for raspberry pi systems and includes a demonstration program.

### CODE REVIEW

**Comment by suraj2596** [comment]
Hi @edwinolson, 

Could you please briefly highlight the improvements in running your code on pi v/s the generic apriltags code? 

Thanks

**Comment by christian-rauch** [comment]
I am against adding device-specific image I/O to the core `apriltag` library. It just adds external dependencies that will not benefit most users of the library. Even the current jpeg decoder is only useful for testing and a proper application will likely provide the raw data to the API. You can always write your own executable and link the required functions from the `apriltag` library.

@mkrogius @wxmerkt What is your opinion on adding device-specific code to the library?

Other comments:
- The project should only use a single build system: either `make` or `cmake`.Any changes to the build system should be made to the `CMakeLists.txt`.
- Squash your commits and give them a proper commit message. I will not accept "wip" commits or anything thereof.
- Since creating this PR the `mmal` interface has been deprecated in favour of `libcamera`. See the [announcement](https://libcamera.org/entries/2020-05-05.html) and the [examples](https://www.raspberrypi.com/documentation/accessories/camera.html#libcamera-and-libcamera-apps).

If @mkrogius and @wxmerkt are ok with adding additional dependencies for image I/O, you probably will have to port this PR to libcamera. If you willing to do this, we can leave this PR open. Otherwise I would just close it for now.

**Comment by s-trinh** [comment]
What about merging these changes into a separate branch?

This way, you could advertise these changes for RPi and let users use it without touching the master branch.

**Comment by christian-rauch** [comment]
I am going to close this as I think that this library should not contain hardware-specific code. Additionally, the hardware interface proposed here (mmal) is deprecated and has been replaced by libcamera.

I don't see the point of adding all those specific dependencies just for demonstrating this on a Raspberry Pi. You can always write a custom demo program that uses hardware-specific interfaces and the apriltag library to demonstrate the AprilTag detection on specific devices.

**Pull request closed without merging**
