### PR TITLE
[cmake] fix include path so that we can include <apriltag/apriltag.h>

### PR DESCRIPTION
**Pull request by simogasp**
The include directory when using apriltag as a 3rd party points to `install/path/include/apriltag/` which it is not what you really want if you want to include the headers using the prefix `apriltag` (to e.g. avoid potential name conflicts)
This fix also add `install/path/include/` to the search path so that we can `#include <apriltag/apriltag.hpp>`.
I kept the other to avoid breaking the compatibility with previous versions (i.e. so including `#include <apriltag.hpp>` still works but I'd not recommend itit).

### CODE REVIEW

**Comment by fabiencastan** [comment]
It would be great to merge this PR.

This small issue is preventing us from integrating AprilTag into AliceVision:
https://github.com/alicevision/AliceVision/pull/950

Thanks for your time.

**Comment by fabiencastan** [comment]
Any feedback?

**Comment by mkrogius** [comment]
Apologies for the delay, I didn't really understand the change, but now I've read up more on this part of cmake.

**Comment by fabiencastan** [comment]
Thanks!

**Pull request merged**
